/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import javax.swing.JOptionPane;
import logica.ArrayUsuarios;
import logica.Usuario;
import logica.Bicicleta;
/**
 *
 * @author 
 */
public class VentanaActualizarUsuario extends javax.swing.JFrame {
    public byte contador=0;
    public double km;
    public double tiempoHoras;

    public VentanaActualizarUsuario() {
        initComponents();
        cargarCombo();
    }
    private void cargarCombo() {
    comboUsuarios.removeAllItems();
    for (Usuario u : ArrayUsuarios.getUsuarios()) {
        comboUsuarios.addItem(u);  
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnEstadoCasco = new javax.swing.JButton();
        btnMostrarDatos = new javax.swing.JButton();
        btnCascoPuesto = new javax.swing.JButton();
        btnEditarNombre = new javax.swing.JButton();
        btnEditarEdad = new javax.swing.JButton();
        btnViaje = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnRevisarBici = new javax.swing.JButton();
        btnInflar = new javax.swing.JButton();
        btnCambiarCambios = new javax.swing.JButton();
        btnCambiosActuales = new javax.swing.JButton();
        btnNecesitaInflado = new javax.swing.JButton();
        comboUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Usuario y Bicicleta");
        setName("Gestión de Usuario y Bicicleta"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(33, 27, 44));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizacion Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBackground(new java.awt.Color(61, 50, 69));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel4.setBackground(new java.awt.Color(33, 27, 44));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        jPanel9.setBackground(new java.awt.Color(61, 50, 69));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEstadoCasco.setBackground(new java.awt.Color(33, 27, 44));
        btnEstadoCasco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEstadoCasco.setText("Poner/quitar casco");
        btnEstadoCasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoCascoActionPerformed(evt);
            }
        });

        btnMostrarDatos.setBackground(new java.awt.Color(33, 27, 44));
        btnMostrarDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarDatos.setText("Mostrar datos");
        btnMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatosActionPerformed(evt);
            }
        });

        btnCascoPuesto.setBackground(new java.awt.Color(33, 27, 44));
        btnCascoPuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCascoPuesto.setText("Se tiene el casco puesto?");
        btnCascoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCascoPuestoActionPerformed(evt);
            }
        });

        btnEditarNombre.setBackground(new java.awt.Color(33, 27, 44));
        btnEditarNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarNombre.setText("Editar nombre");
        btnEditarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNombreActionPerformed(evt);
            }
        });

        btnEditarEdad.setBackground(new java.awt.Color(33, 27, 44));
        btnEditarEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarEdad.setText("Editar edad");
        btnEditarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEdadActionPerformed(evt);
            }
        });

        btnViaje.setBackground(new java.awt.Color(33, 27, 44));
        btnViaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViaje.setText("Hacer Viaje");
        btnViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCascoPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(btnEstadoCasco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstadoCasco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCascoPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarDatos)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(33, 27, 44));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bicicleta");

        jPanel8.setBackground(new java.awt.Color(61, 50, 69));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnRevisarBici.setBackground(new java.awt.Color(33, 27, 44));
        btnRevisarBici.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRevisarBici.setText("Revisar bicicleta");
        btnRevisarBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarBiciActionPerformed(evt);
            }
        });

        btnInflar.setBackground(new java.awt.Color(33, 27, 44));
        btnInflar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInflar.setText("Inflar ruedas");
        btnInflar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInflarActionPerformed(evt);
            }
        });

        btnCambiarCambios.setBackground(new java.awt.Color(33, 27, 44));
        btnCambiarCambios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiarCambios.setText("Cambiar cambios");
        btnCambiarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCambiosActionPerformed(evt);
            }
        });

        btnCambiosActuales.setBackground(new java.awt.Color(33, 27, 44));
        btnCambiosActuales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiosActuales.setText("Cambios actuales");
        btnCambiosActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosActualesActionPerformed(evt);
            }
        });

        btnNecesitaInflado.setBackground(new java.awt.Color(33, 27, 44));
        btnNecesitaInflado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNecesitaInflado.setText("Necesita inflado?");
        btnNecesitaInflado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNecesitaInfladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiosActuales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInflar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRevisarBici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambiarCambios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNecesitaInflado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRevisarBici)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInflar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiosActuales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNecesitaInflado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        comboUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        comboUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        comboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsuariosActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icons/usermorao.png"))); // NOI18N
        jLabel1.setText("Usuario:");

        txtArea.setBackground(new java.awt.Color(33, 27, 44));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setText("Elija un usuario y toque un botón para aplicarle un método");
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(61, 50, 69));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setBackground(new java.awt.Color(61, 50, 69));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icons/clipboard.png"))); // NOI18N
        jLabel4.setText("ventana de actualización de datos");
        jLabel4.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(61, 50, 69));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icons/back-buttonSmall.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajeActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        double km;
        double tiempoHoras;
        String kmStr;
        String tiempoHorasStr;

        if(UsuarioSelec.isCascoPuesto()){
            kmStr = JOptionPane.showInputDialog("Ingrese los km recorridos: ");
            km = Integer.parseInt(kmStr);
            tiempoHorasStr = JOptionPane.showInputDialog("Ingrese las horas andadas: ");
            tiempoHoras = Integer.parseInt(tiempoHorasStr);

            UsuarioSelec.hacerViaje(km, tiempoHoras);
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo realizar el viaje, el casco no está puesto");
        }
    }//GEN-LAST:event_btnViajeActionPerformed

    private void comboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUsuariosActionPerformed

    private void btnCambiosActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosActualesActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        Bicicleta bici = UsuarioSelec.getBici();

        txtArea.setText("La bici esta en el cambio "+bici.getCambiosActuales());
    }//GEN-LAST:event_btnCambiosActualesActionPerformed

    private void btnInflarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInflarActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        Bicicleta bici = UsuarioSelec.getBici();
        double cantidad;
        String cantidadStr;

        cantidadStr = JOptionPane.showInputDialog("Cuanto desea inflar las ruedas?: ");
        cantidad = Double.parseDouble(cantidadStr);

        if(cantidad <= 70  && cantidad >= 0){
            bici.setPresionNeumaticos(cantidad);
        }
        else{
            JOptionPane.showMessageDialog(this, "El numero ingresado escapa de los parametros establecidos");
        }

        txtArea.setText("La presion actual de los neumaticos es "+bici.getPresionNeumaticos());
    }//GEN-LAST:event_btnInflarActionPerformed

    private void btnNecesitaInfladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNecesitaInfladoActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        Bicicleta bici = UsuarioSelec.getBici();

        if(bici.necesitaInflado()){
            txtArea.setText("La bici necesita inflado");
        }
        else{
            txtArea.setText("La bici no necesita inflado");
        }
    }//GEN-LAST:event_btnNecesitaInfladoActionPerformed

    private void btnEditarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEdadActionPerformed
    
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        String edadStr = JOptionPane.showInputDialog("Ingrese la nueva edad: ");
        if(edadStr.isEmpty()){
        JOptionPane.showMessageDialog(this, "la edad no puede estar vacio");
        return;
        }
        int edad = Integer.parseInt(edadStr);
        UsuarioSelec.setEdad(edad);
        txtArea.setText("La edad es ahora: "+edad);
    }//GEN-LAST:event_btnEditarEdadActionPerformed

    private void btnEditarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNombreActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        String nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
        if(nombre.isEmpty()){
        JOptionPane.showMessageDialog(this, "el nombre no puede estar vacio");
        return;
        }
        UsuarioSelec.setNombre(nombre);
        txtArea.setText("El nombre es ahora: "+nombre);
    }//GEN-LAST:event_btnEditarNombreActionPerformed

    private void btnCascoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCascoPuestoActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        if(UsuarioSelec.isCascoPuesto()){
            txtArea.setText("El casco esta puesto");
        }
        else{
            txtArea.setText("El casco no esta puesto");
        }
    }//GEN-LAST:event_btnCascoPuestoActionPerformed

    private void btnMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatosActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        txtArea.setText(UsuarioSelec.toString());
    }//GEN-LAST:event_btnMostrarDatosActionPerformed

    private void btnEstadoCascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoCascoActionPerformed

        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();

        if (UsuarioSelec.isCascoPuesto()){
            txtArea.setText("Se quitó el casco");
            UsuarioSelec.sacarCasco();
        }
        else{
            txtArea.setText("Se puso el casco");
            UsuarioSelec.ponerCasco();
        }
    }//GEN-LAST:event_btnEstadoCascoActionPerformed

    private void btnRevisarBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarBiciActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();

        if(UsuarioSelec.revisarBicicleta().equals("")){
            txtArea.setText("La bici no necesita nada");
        }
        else{
            txtArea.setText("La bicicleta precisa "+UsuarioSelec.revisarBicicleta());
        }
    }//GEN-LAST:event_btnRevisarBiciActionPerformed

    private void btnCambiarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCambiosActionPerformed
        Usuario UsuarioSelec =(Usuario) comboUsuarios.getSelectedItem();
        Bicicleta bici = UsuarioSelec.getBici();
        int cambio;
        String cambioStr;

        cambioStr = JOptionPane.showInputDialog("A que cambio desea cambiar?: ");
        cambio = Integer.parseInt(cambioStr);

        if(cambio <= 7 && cambio >= 1){
            txtArea.setText("Ahora se esta en el cambio numero "+cambio);
        }
        else{
            JOptionPane.showMessageDialog(this, "El numero ingresado escapa de los parametros establecidos");
        }
    }//GEN-LAST:event_btnCambiarCambiosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
        new ventanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaActualizarUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarCambios;
    private javax.swing.JButton btnCambiosActuales;
    private javax.swing.JButton btnCascoPuesto;
    private javax.swing.JButton btnEditarEdad;
    private javax.swing.JButton btnEditarNombre;
    private javax.swing.JButton btnEstadoCasco;
    private javax.swing.JButton btnInflar;
    private javax.swing.JButton btnMostrarDatos;
    private javax.swing.JButton btnNecesitaInflado;
    private javax.swing.JButton btnRevisarBici;
    private javax.swing.JButton btnViaje;
    private javax.swing.JComboBox<Usuario> comboUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables


}

